name: flutter_hive_tdo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_beautiful_popup: ^1.7.0
  flutter_cupertino_date_picker_fork: ^1.0.7
  flutter_datetime_picker: ^1.5.1
  flutter_slider_drawer: ^2.1.3
  ftoast: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  lottie: ^3.1.0
  panara_dialogs: ^0.1.4
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
